/* ============================================================
   A1 课程内容（完整）
   单词格式：[德语, 中文, 读音提示, 例句, 例句译文, 词性]
     - 名词带上冠词，如 'die Familie'
     - 例句用 { } 标出可挖空部分
     - 词性：n 名词 / v 动词 / a 形容词 / x 其他
   lv 表示 CEFR 等级
   ============================================================ */
window.CONTENT_A1 = [
{t:'问候与道别', lv:'A1', s:'Begrüßung', w:[
 ['Hallo','你好（随意）','哈洛','{Hallo}, ich bin Li.','你好，我是李。','x'],
 ['Guten Morgen','早上好','古腾 摩根','{Guten Morgen}, Frau Müller!','早上好，穆勒女士！','x'],
 ['Guten Tag','你好（白天正式）','古腾 塔克','{Guten Tag}, wie geht es Ihnen?','您好，您过得好吗？','x'],
 ['Guten Abend','晚上好','古腾 阿本特','{Guten Abend}, Herr Schmidt.','晚上好，施密特先生。','x'],
 ['Gute Nacht','晚安','古特 纳赫特','{Gute Nacht}, schlaf gut!','晚安，睡个好觉！','x'],
 ['Tschüss','再见（随意）','去斯','{Tschüss}, bis morgen!','再见，明天见！','x'],
 ['Auf Wiedersehen','再见（正式）','奥夫 维德泽恩','{Auf Wiedersehen}, Frau Doktor.','再见，博士女士。','x'],
 ['Danke','谢谢','当克','{Danke} für die Hilfe!','谢谢帮忙！','x'],
 ['Bitte','请／不客气','比特','{Bitte}, kommen Sie herein.','请进。','x'],
 ['Entschuldigung','对不起／劳驾','恩特舒尔迪贡','{Entschuldigung}, wo ist der Bahnhof?','劳驾，火车站在哪里？','x']
]},
{t:'认识与自我介绍', lv:'A1', s:'Sich vorstellen', w:[
 ['ich','我','伊希','{Ich} heiße Anna.','我叫安娜。','x'],
 ['du','你（对熟人）','杜','Wie heißt {du}?','你叫什么名字？','x'],
 ['Sie','您（尊称）','兹','Wie heißen {Sie}?','您怎么称呼？','x'],
 ['sein','是','再恩','Ich {bin} aus China.','我来自中国。','v'],
 ['heißen','名叫','海森','Wie {heißen} Sie?','您叫什么名字？','v'],
 ['kommen','来，来自','科门','Ich {komme} aus Deutschland.','我来自德国。','v'],
 ['wohnen','居住','沃嫩','Ich {wohne} in Berlin.','我住在柏林。','v'],
 ['der Name','名字','纳默','Mein {Name} ist Li Wei.','我的名字是李伟。','n'],
 ['das Land','国家','兰特','Aus welchem {Land} kommen Sie?','您来自哪个国家？','n'],
 ['die Sprache','语言','施普拉赫','Deutsch ist eine schöne {Sprache}.','德语是一门美丽的语言。','n']
]},
{t:'数字 0–12', lv:'A1', s:'Zahlen', w:[
 ['null','零','努尔','Die Temperatur ist {null} Grad.','温度是零度。','x'],
 ['eins','一','艾恩斯','Ich möchte {eins} von diesen.','我想要其中一个。','x'],
 ['zwei','二','次外','Ich habe {zwei} Schwestern.','我有两个姐妹。','x'],
 ['drei','三','德赖','Das kostet {drei} Euro.','这个三欧元。','x'],
 ['vier','四','菲尔','Wir sind {vier} Personen.','我们四个人。','x'],
 ['fünf','五','弗恩夫','Ich arbeite {fünf} Tage pro Woche.','我每周工作五天。','x'],
 ['sechs','六','泽克斯','Es ist {sechs} Uhr.','现在六点。','x'],
 ['sieben','七','济本','Die Woche hat {sieben} Tage.','一周有七天。','x'],
 ['acht','八','阿赫特','Ich stehe um {acht} Uhr auf.','我八点起床。','x'],
 ['neun','九','诺伊恩','Der Kurs beginnt um {neun}.','课程九点开始。','x'],
 ['zehn','十','岑','Ich zähle bis {zehn}.','我数到十。','x'],
 ['elf','十一','艾尔夫','Es ist {elf} Uhr.','现在十一点。','x'],
 ['zwölf','十二','次沃尔夫','Das Jahr hat {zwölf} Monate.','一年有十二个月。','x']
]},
{t:'数字 13–100', lv:'A1', s:'Zahlen II', w:[
 ['dreizehn','十三','德赖岑','Mein Bruder ist {dreizehn} Jahre alt.','我弟弟十三岁。','x'],
 ['vierzehn','十四','菲尔岑','Sie ist {vierzehn}.','她十四岁。','x'],
 ['fünfzehn','十五','弗恩夫岑','Das kostet {fünfzehn} Euro.','这个十五欧元。','x'],
 ['sechzehn','十六','泽希岑','Mit {sechzehn} darf man Auto fahren.','十六岁可以开车。','x'],
 ['siebzehn','十七','济普岑','Er ist {siebzehn} Jahre alt.','他十七岁。','x'],
 ['achtzehn','十八','阿赫特岑','Mit {achtzehn} ist man volljährig.','十八岁成年。','x'],
 ['neunzehn','十九','诺伊恩岑','Sie wohnt in Zimmer {neunzehn}.','她住在十九号房间。','x'],
 ['zwanzig','二十','次万齐希','Ich habe {zwanzig} Euro.','我有二十欧元。','x'],
 ['dreißig','三十','德赖西希','Der Monat hat {dreißig} Tage.','这个月有三十天。','x'],
 ['hundert','一百','洪德特','Das kostet {hundert} Euro.','这个一百欧元。','x']
]},
{t:'基础动词', lv:'A1', s:'Grundverben', w:[
 ['gehen','走，去','给恩','Ich {gehe} nach Hause.','我回家。','v'],
 ['sprechen','说，讲','施普雷贤','{Sprechen} Sie Deutsch?','您说德语吗？','v'],
 ['verstehen','理解','费施泰恩','Ich {verstehe} nicht.','我不明白。','v'],
 ['lernen','学习','雷恩恩','Ich {lerne} Deutsch.','我在学德语。','v'],
 ['arbeiten','工作','阿拜滕','Wo {arbeiten} Sie?','您在哪里工作？','v'],
 ['kaufen','买','考芬','Ich möchte Brot {kaufen}.','我想买面包。','v'],
 ['essen','吃','艾森','Wir {essen} um sieben.','我们七点吃饭。','v'],
 ['trinken','喝','特林肯','Ich {trinke} gern Kaffee.','我喜欢喝咖啡。','v'],
 ['schlafen','睡觉','施拉芬','Ich {schlafe} acht Stunden.','我睡八小时。','v'],
 ['lesen','读','雷曾','Ich {lese} ein Buch.','我在读一本书。','v']
]},
{t:'家庭', lv:'A1', s:'Die Familie', w:[
 ['die Familie','家庭','法米利厄','Meine {Familie} ist groß.','我的家庭很大。','n'],
 ['die Mutter','母亲','穆特','Meine {Mutter} kocht gut.','我妈妈做饭很好吃。','n'],
 ['der Vater','父亲','法特','Mein {Vater} arbeitet viel.','我爸爸工作很多。','n'],
 ['der Bruder','兄弟','布鲁德','Mein {Bruder} ist zehn.','我弟弟十岁。','n'],
 ['die Schwester','姐妹','施韦斯特','Meine {Schwester} wohnt in Köln.','我姐姐住在科隆。','n'],
 ['das Kind','孩子','金特','Das {Kind} spielt im Garten.','孩子在花园里玩。','n'],
 ['der Sohn','儿子','佐恩','Ihr {Sohn} ist Student.','她儿子是大学生。','n'],
 ['die Tochter','女儿','托赫特','Meine {Tochter} geht zur Schule.','我女儿上学。','n'],
 ['die Eltern','父母','艾尔滕','Meine {Eltern} wohnen in Beijing.','我父母住在北京。','n'],
 ['der Mann','男人／丈夫','曼','Ihr {Mann} ist Arzt.','她丈夫是医生。','n']
]},
{t:'饮食', lv:'A1', s:'Essen und Trinken', w:[
 ['das Brot','面包','布洛特','Ich kaufe frisches {Brot}.','我买新鲜面包。','n'],
 ['das Wasser','水','瓦瑟','Ein Glas {Wasser}, bitte.','请来一杯水。','n'],
 ['der Kaffee','咖啡','卡费','Ich trinke {Kaffee} ohne Zucker.','我喝咖啡不加糖。','n'],
 ['der Tee','茶','泰','Möchten Sie {Tee} oder Kaffee?','您想要茶还是咖啡？','n'],
 ['das Bier','啤酒','比尔','Ein {Bier}, bitte!','请来一杯啤酒！','n'],
 ['die Milch','牛奶','米尔希','Ich trinke {Milch} zum Frühstück.','我早餐喝牛奶。','n'],
 ['der Käse','奶酪','凯泽','Der {Käse} kommt aus der Schweiz.','这奶酪来自瑞士。','n'],
 ['der Apfel','苹果','阿普费尔','Ein {Apfel} am Tag ist gesund.','一天一苹果，身体好。','n'],
 ['das Fleisch','肉','弗莱施','Ich esse kein {Fleisch}.','我不吃肉。','n'],
 ['die Suppe','汤','祖佩','Die {Suppe} ist heiß.','汤很烫。','n']
]},
{t:'餐厅', lv:'A1', s:'Im Restaurant', w:[
 ['die Speisekarte','菜单','施派泽卡特','Die {Speisekarte}, bitte.','请给我菜单。','n'],
 ['bestellen','点（菜）','贝施泰伦','Ich möchte {bestellen}.','我想点菜。','v'],
 ['die Rechnung','账单','雷希农','Die {Rechnung}, bitte!','请结账！','n'],
 ['bezahlen','付款','贝曹伦','Wir möchten {bezahlen}.','我们想结账。','v'],
 ['der Kellner','服务员','凯尔纳','Der {Kellner} bringt das Wasser.','服务员端来水。','n'],
 ['das Frühstück','早餐','弗吕施图克','Das {Frühstück} ist inklusive.','含早餐。','n'],
 ['das Mittagessen','午餐','米塔克艾森','Zum {Mittagessen} esse ich Reis.','午饭我吃米饭。','n'],
 ['das Abendessen','晚餐','阿本特艾森','Das {Abendessen} war lecker.','晚餐很好吃。','n'],
 ['lecker','好吃的','莱克','Der Kuchen ist sehr {lecker}.','这个蛋糕很好吃。','a'],
 ['satt','饱的','扎特','Ich bin {satt}.','我吃饱了。','a']
]},
{t:'时间与日期', lv:'A1', s:'Zeit und Datum', w:[
 ['die Uhr','钟／点钟','乌尔','Es ist drei {Uhr}.','现在三点。','n'],
 ['die Stunde','小时','施图恩德','Ich warte eine {Stunde}.','我等一小时。','n'],
 ['die Minute','分钟','米努特','Warten Sie eine {Minute}.','请等一分钟。','n'],
 ['der Tag','天','塔克','Jeden {Tag} lerne ich Deutsch.','我每天学德语。','n'],
 ['die Woche','星期','沃赫','Diese {Woche} habe ich Zeit.','这周我有时间。','n'],
 ['der Monat','月','莫纳特','Der Kurs dauert einen {Monat}.','课程持续一个月。','n'],
 ['das Jahr','年','亚尔','Ich lerne ein {Jahr} Deutsch.','我学德语一年了。','n'],
 ['heute','今天','霍伊特','{Heute} ist Montag.','今天是星期一。','x'],
 ['morgen','明天','摩根','{Morgen} fahre ich nach Berlin.','明天我去柏林。','x'],
 ['gestern','昨天','格斯特恩','{Gestern} war ich müde.','昨天我很累。','x']
]},
{t:'城市与交通', lv:'A1', s:'Stadt und Verkehr', w:[
 ['die Stadt','城市','施塔特','München ist eine schöne {Stadt}.','慕尼黑是座美丽的城市。','n'],
 ['der Bahnhof','火车站','班霍夫','Wo ist der {Bahnhof}?','火车站在哪里？','n'],
 ['der Zug','火车','楚克','Der {Zug} fährt um acht.','火车八点开。','n'],
 ['der Bus','公交车','布斯','Ich nehme den {Bus}.','我坐公交车。','n'],
 ['die Straße','街道','施特拉瑟','Ich wohne in dieser {Straße}.','我住在这条街。','n'],
 ['das Auto','汽车','奥托','Mein {Auto} ist alt.','我的车很旧。','n'],
 ['die Fahrkarte','车票','法尔卡特','Eine {Fahrkarte} nach Berlin, bitte.','请给我一张去柏林的车票。','n'],
 ['fahren','行驶，乘车','法伦','Ich {fahre} nach Hamburg.','我去汉堡。','v'],
 ['der Flughafen','机场','弗卢克哈芬','Der {Flughafen} ist weit.','机场很远。','n'],
 ['das Flugzeug','飞机','弗卢克措伊克','Das {Flugzeug} landet um zehn.','飞机十点降落。','n']
]},
{t:'购物', lv:'A1', s:'Einkaufen', w:[
 ['das Geschäft','商店','格舍夫特','Das {Geschäft} ist geschlossen.','商店关门了。','n'],
 ['der Markt','市场','马尔克特','Ich gehe auf den {Markt}.','我去市场。','n'],
 ['der Preis','价格','普赖斯','Der {Preis} ist zu hoch.','价格太高了。','n'],
 ['das Geld','钱','盖尔特','Ich habe kein {Geld}.','我没钱。','n'],
 ['der Euro','欧元','奥伊罗','Das kostet zehn {Euro}.','这个十欧元。','n'],
 ['teuer','贵的','托伊尔','Das ist zu {teuer}.','这太贵了。','a'],
 ['billig','便宜的','比利希','Das ist sehr {billig}.','这很便宜。','a'],
 ['die Kasse','收银台','卡瑟','Bitte zahlen Sie an der {Kasse}.','请在收银台付款。','n'],
 ['die Größe','尺码／大小','格勒瑟','Welche {Größe} brauchen Sie?','您要哪个尺码？','n'],
 ['anprobieren','试穿','安普罗比伦','Kann ich das {anprobieren}?','我可以试穿吗？','v']
]},
{t:'住宿', lv:'A1', s:'Im Hotel', w:[
 ['das Hotel','酒店','霍特尔','Das {Hotel} ist im Zentrum.','酒店在市中心。','n'],
 ['das Zimmer','房间','齐默','Ich brauche ein {Zimmer}.','我需要一个房间。','n'],
 ['der Schlüssel','钥匙','施吕瑟尔','Hier ist Ihr {Schlüssel}.','这是您的钥匙。','n'],
 ['die Rezeption','前台','雷采普齐翁','Fragen Sie an der {Rezeption}.','请到前台询问。','n'],
 ['die Dusche','淋浴','杜舍','Das Zimmer hat eine {Dusche}.','房间有淋浴。','n'],
 ['das Bett','床','贝特','Das {Bett} ist bequem.','床很舒服。','n'],
 ['die Nacht','夜','纳赫特','Eine {Nacht} kostet 80 Euro.','一晚80欧。','n'],
 ['frei','空着的','弗赖','Ist noch ein Zimmer {frei}?','还有空房吗？','a'],
 ['reservieren','预订','雷泽维伦','Ich möchte ein Zimmer {reservieren}.','我想预订一个房间。','v'],
 ['der Gast','客人','加斯特','Der {Gast} kommt um sechs.','客人六点到。','n']
]},
{t:'身体与健康', lv:'A1', s:'Körper und Gesundheit', w:[
 ['der Kopf','头','科普夫','Mein {Kopf} tut weh.','我头疼。','n'],
 ['das Auge','眼睛','奥格','Ihr {Auge} ist blau.','她眼睛是蓝色的。','n'],
 ['die Hand','手','汉特','Gib mir deine {Hand}.','把手给我。','n'],
 ['der Fuß','脚','弗斯','Mein {Fuß} ist kalt.','我的脚很冷。','n'],
 ['der Arm','胳膊','阿尔姆','Sein {Arm} ist gebrochen.','他胳膊骨折了。','n'],
 ['das Bein','腿','拜恩','Mein {Bein} tut weh.','我腿疼。','n'],
 ['der Bauch','肚子','包赫','Mein {Bauch} ist voll.','我肚子饱了。','n'],
 ['krank','生病的','克兰克','Ich bin {krank}.','我生病了。','a'],
 ['gesund','健康的','格尊特','Obst ist {gesund}.','水果很健康。','a'],
 ['der Arzt','医生','阿尔茨特','Ich gehe zum {Arzt}.','我去看医生。','n']
]},
{t:'天气与季节', lv:'A1', s:'Wetter und Jahreszeiten', w:[
 ['das Wetter','天气','韦特','Das {Wetter} ist schön.','天气很好。','n'],
 ['die Sonne','太阳','佐内','Die {Sonne} scheint.','太阳在照耀。','n'],
 ['der Regen','雨','雷根','Heute gibt es {Regen}.','今天有雨。','n'],
 ['der Schnee','雪','施内','Im Winter liegt {Schnee}.','冬天有雪。','n'],
 ['der Wind','风','温特','Der {Wind} ist stark.','风很大。','n'],
 ['warm','暖的','瓦尔姆','Es ist heute {warm}.','今天很暖和。','a'],
 ['kalt','冷的','卡尔特','Im Winter ist es {kalt}.','冬天很冷。','a'],
 ['der Sommer','夏天','佐默','Im {Sommer} fahren wir ans Meer.','夏天我们去海边。','n'],
 ['der Winter','冬天','温特','Der {Winter} ist lang.','冬天很长。','n'],
 ['der Frühling','春天','弗吕林','Im {Frühling} blühen die Blumen.','春天花开了。','n']
]},
{t:'常用形容词', lv:'A1', s:'Adjektive', w:[
 ['gut','好的','古特','Das Essen ist {gut}.','饭菜很好。','a'],
 ['schlecht','坏的','施莱希特','Das Wetter ist {schlecht}.','天气很糟。','a'],
 ['groß','大的','格罗斯','Berlin ist eine {große} Stadt.','柏林是座大城市。','a'],
 ['klein','小的','克莱恩','Das Zimmer ist {klein}.','房间很小。','a'],
 ['alt','老的','阿尔特','Mein Auto ist {alt}.','我的车很旧。','a'],
 ['neu','新的','诺伊','Das ist ein {neues} Handy.','这是新手机。','a'],
 ['schön','美的','舍恩','Der Garten ist {schön}.','花园很美。','a'],
 ['schnell','快的','施内尔','Der Zug ist {schnell}.','火车很快。','a'],
 ['langsam','慢的','朗扎姆','Bitte sprechen Sie {langsam}.','请说慢一点。','a'],
 ['müde','累的','米德','Ich bin sehr {müde}.','我很累。','a']
]},
{t:'情态动词与常用表达', lv:'A1', s:'Modalverben', w:[
 ['können','能，会','克嫩','Ich {kann} Deutsch sprechen.','我会说德语。','v'],
 ['müssen','必须','米森','Ich {muss} jetzt gehen.','我现在必须走了。','v'],
 ['wollen','想要','沃伦','Wir {wollen} nach Berlin fahren.','我们想去柏林。','v'],
 ['möchten','想要（礼貌）','默希滕','Ich {möchte} einen Kaffee.','我想要一杯咖啡。','v'],
 ['dürfen','被允许','迪尔芬','Hier {darf} man nicht rauchen.','这里不许吸烟。','v'],
 ['sollen','应该','佐伦','Was {soll} ich tun?','我该怎么办？','v'],
 ['gern','乐意地','盖恩','Ich trinke {gern} Tee.','我喜欢喝茶。','x'],
 ['vielleicht','也许','菲尔莱希特','{Vielleicht} komme ich später.','也许我晚点来。','x'],
 ['natürlich','当然','纳蒂尔利希','{Natürlich} helfe ich dir.','我当然帮你。','x'],
 ['leider','可惜，遗憾','莱德','{Leider} habe ich keine Zeit.','很遗憾我没时间。','x']
]},
{t:'服装', lv:'A1', s:'Kleidung', w:[
 ['die Kleidung','衣服（总称）','克莱东','Diese {Kleidung} ist teuer.','这件衣服很贵。','n'],
 ['das Hemd','衬衫','赫姆特','Das {Hemd} ist zu klein.','这件衬衫太小。','n'],
 ['die Hose','裤子','霍泽','Die {Hose} passt gut.','这条裤子很合身。','n'],
 ['das Kleid','连衣裙','克莱特','Das {Kleid} ist schön.','这条裙子很漂亮。','n'],
 ['die Jacke','外套','雅克','Nimm die {Jacke} mit!','带上外套！','n'],
 ['der Schuh','鞋','舒','Der {Schuh} ist neu.','这鞋是新的。','n'],
 ['die Socke','袜子','佐克','Ich brauche warme {Socken}.','我需要保暖的袜子。','n'],
 ['der Mantel','大衣','曼特尔','Der {Mantel} ist warm.','这件大衣很暖和。','n'],
 ['der Rock','半身裙','罗克','Der {Rock} ist kurz.','这条裙子很短。','n'],
 ['die Tasche','包','塔舍','Meine {Tasche} ist schwer.','我的包很重。','n']
]},
{t:'颜色', lv:'A1', s:'Farben', w:[
 ['die Farbe','颜色','法尔贝','Welche {Farbe} magst du?','你喜欢哪个颜色？','n'],
 ['rot','红色的','罗特','Das Auto ist {rot}.','这辆车是红色的。','a'],
 ['blau','蓝色的','布劳','Der Himmel ist {blau}.','天空是蓝色的。','a'],
 ['grün','绿色的','格吕恩','Das Gras ist {grün}.','草是绿色的。','a'],
 ['gelb','黄色的','格尔普','Die Sonne ist {gelb}.','太阳是黄色的。','a'],
 ['schwarz','黑色的','施瓦茨','Ich trage {schwarz}.','我穿黑色。','a'],
 ['weiß','白色的','外斯','Der Schnee ist {weiß}.','雪是白色的。','a'],
 ['grau','灰色的','格劳','Der Himmel ist {grau}.','天空是灰色的。','a'],
 ['braun','棕色的','布劳恩','Ihre Augen sind {braun}.','她的眼睛是棕色的。','a'],
 ['bunt','彩色的','布恩特','Die Blumen sind {bunt}.','花是彩色的。','a']
]},
{t:'住房', lv:'A1', s:'Wohnen', w:[
 ['die Wohnung','公寓','沃农','Meine {Wohnung} ist klein.','我的公寓很小。','n'],
 ['das Haus','房子','豪斯','Das {Haus} ist alt.','这房子很老。','n'],
 ['das Wohnzimmer','客厅','沃恩齐默','Wir sitzen im {Wohnzimmer}.','我们坐在客厅。','n'],
 ['die Küche','厨房','屈赫','Die {Küche} ist modern.','厨房很现代。','n'],
 ['das Bad','浴室','巴特','Das {Bad} ist sauber.','浴室很干净。','n'],
 ['das Schlafzimmer','卧室','施拉夫齐默','Das {Schlafzimmer} ist groß.','卧室很大。','n'],
 ['der Tisch','桌子','蒂施','Das Buch liegt auf dem {Tisch}.','书在桌上。','n'],
 ['der Stuhl','椅子','施图尔','Der {Stuhl} ist bequem.','椅子很舒服。','n'],
 ['das Fenster','窗户','芬斯特','Bitte öffne das {Fenster}.','请打开窗户。','n'],
 ['die Tür','门','蒂尔','Mach die {Tür} zu!','把门关上！','n']
]},
{t:'学校与学习', lv:'A1', s:'Schule und Lernen', w:[
 ['die Schule','学校','舒勒','Mein Sohn geht zur {Schule}.','我儿子上学。','n'],
 ['die Universität','大学','乌尼维西泰特','Sie studiert an der {Universität}.','她在上大学。','n'],
 ['der Kurs','课程','库尔斯','Der {Kurs} beginnt morgen.','课程明天开始。','n'],
 ['der Lehrer','老师','雷雷尔','Unser {Lehrer} ist nett.','我们老师很友好。','n'],
 ['der Student','大学生','施图登特','Er ist {Student}.','他是大学生。','n'],
 ['das Buch','书','布赫','Das {Buch} ist interessant.','这本书很有趣。','n'],
 ['der Stift','笔','施蒂夫特','Ich brauche einen {Stift}.','我需要一支笔。','n'],
 ['die Aufgabe','作业／任务','奥夫加贝','Die {Aufgabe} ist schwer.','这道题很难。','n'],
 ['die Prüfung','考试','普吕丰','Die {Prüfung} ist am Montag.','考试在星期一。','n'],
 ['die Frage','问题','弗拉格','Ich habe eine {Frage}.','我有一个问题。','n']
]},
{t:'职业', lv:'A1', s:'Berufe', w:[
 ['der Beruf','职业','贝鲁夫','Was ist Ihr {Beruf}?','您的职业是什么？','n'],
 ['die Arbeit','工作','阿尔拜特','Die {Arbeit} macht Spaß.','这工作很有意思。','n'],
 ['der Ingenieur','工程师','因热尼厄尔','Er ist {Ingenieur}.','他是工程师。','n'],
 ['der Verkäufer','售货员','费尔科伊费尔','Der {Verkäufer} ist freundlich.','售货员很友好。','n'],
 ['der Koch','厨师','科赫','Der {Koch} arbeitet viel.','厨师工作很多。','n'],
 ['der Fahrer','司机','法雷尔','Der {Fahrer} wartet.','司机在等。','n'],
 ['die Krankenschwester','护士','克兰肯施韦斯特','Sie ist {Krankenschwester}.','她是护士。','n'],
 ['der Polizist','警察','波利齐斯特','Der {Polizist} hilft uns.','警察帮助我们。','n'],
 ['der Bauer','农民','包尔','Der {Bauer} hat einen Hof.','农民有一个农场。','n'],
 ['der Journalist','记者','茹尔纳利斯特','Er ist {Journalist}.','他是记者。','n']
]},
{t:'爱好与休闲', lv:'A1', s:'Hobbys', w:[
 ['das Hobby','爱好','霍比','Mein {Hobby} ist Musik.','我的爱好是音乐。','n'],
 ['die Musik','音乐','穆济克','Ich höre gern {Musik}.','我喜欢听音乐。','n'],
 ['das Lied','歌','利特','Das {Lied} ist schön.','这首歌很好听。','n'],
 ['der Film','电影','菲尔姆','Der {Film} war lang.','这部电影很长。','n'],
 ['das Spiel','游戏／比赛','施皮尔','Das {Spiel} macht Spaß.','这个游戏很好玩。','n'],
 ['die Kunst','艺术','库恩斯特','Sie liebt {Kunst}.','她热爱艺术。','n'],
 ['tanzen','跳舞','坦岑','Wir {tanzen} gern.','我们喜欢跳舞。','v'],
 ['singen','唱歌','静恩','Er kann gut {singen}.','他唱歌很好听。','v'],
 ['malen','画画','马伦','Die Kinder {malen} gern.','孩子们喜欢画画。','v'],
 ['fotografieren','拍照','福托格拉菲伦','Ich {fotografiere} gern.','我喜欢拍照。','v']
]},
{t:'运动', lv:'A1', s:'Sport', w:[
 ['der Sport','运动','施波尔特','{Sport} ist gesund.','运动有益健康。','n'],
 ['der Fußball','足球','弗斯巴尔','Er spielt {Fußball}.','他踢足球。','n'],
 ['schwimmen','游泳','施维门','Ich kann gut {schwimmen}.','我游泳游得好。','v'],
 ['laufen','跑','劳芬','Ich {laufe} jeden Morgen.','我每天早上跑步。','v'],
 ['das Fahrrad','自行车','法尔拉特','Ich fahre {Fahrrad}.','我骑自行车。','n'],
 ['spielen','玩，打球','施皮伦','Wir {spielen} Tennis.','我们打网球。','v'],
 ['das Team','团队','蒂姆','Unser {Team} ist stark.','我们队很强。','n'],
 ['gewinnen','赢','格维嫩','Wir wollen {gewinnen}.','我们想赢。','v'],
 ['verlieren','输','费尔利伦','Sie wollen nicht {verlieren}.','他们不想输。','v'],
 ['der Trainer','教练','特雷纳','Der {Trainer} ist streng.','教练很严格。','n']
]},
{t:'日常作息', lv:'A1', s:'Tagesablauf', w:[
 ['aufstehen','起床','奥夫施泰恩','Ich {stehe} um sieben {auf}.','我七点起床。','v'],
 ['frühstücken','吃早餐','弗吕施蒂肯','Wir {frühstücken} um acht.','我们八点吃早餐。','v'],
 ['duschen','淋浴','杜申','Ich {dusche} morgens.','我早上淋浴。','v'],
 ['anziehen','穿衣','安齐恩','Ich muss mich {anziehen}.','我得穿衣服了。','v'],
 ['kochen','做饭','科亨','Meine Mutter {kocht} gut.','我妈妈做饭好吃。','v'],
 ['fernsehen','看电视','费恩泽恩','Abends {sehe} ich {fern}.','晚上我看电视。','v'],
 ['aufräumen','整理','奥夫罗伊门','Bitte {räum} dein Zimmer {auf}.','请整理你的房间。','v'],
 ['einkaufen','购物','安考芬','Ich gehe {einkaufen}.','我去买东西。','v'],
 ['spazieren','散步','施帕齐伦','Wir gehen {spazieren}.','我们去散步。','v'],
 ['schlafen gehen','去睡觉','施拉芬 给恩','Ich will jetzt {schlafen gehen}.','我现在想去睡觉。','v']
]},
{t:'情感与心情', lv:'A1', s:'Gefühle', w:[
 ['glücklich','幸福的','格吕克利希','Ich bin sehr {glücklich}.','我很幸福。','a'],
 ['traurig','悲伤的','特劳里希','Sie ist {traurig}.','她很伤心。','a'],
 ['wütend','生气的','维滕特','Er ist {wütend}.','他很生气。','a'],
 ['nervös','紧张的','内尔沃斯','Ich bin {nervös}.','我很紧张。','a'],
 ['zufrieden','满意的','楚弗里登','Ich bin {zufrieden}.','我很满意。','a'],
 ['überrascht','惊讶的','于贝尔拉施特','Wir sind {überrascht}.','我们很惊讶。','a'],
 ['die Angst','害怕','安格斯特','Ich habe {Angst}.','我害怕。','n'],
 ['die Freude','快乐','弗罗伊德','Die {Freude} ist groß.','非常快乐。','n'],
 ['die Liebe','爱','利贝','{Liebe} ist wichtig.','爱很重要。','n'],
 ['hoffen','希望','霍芬','Ich {hoffe} auf gutes Wetter.','我希望天气好。','v']
]},
{t:'方位与方向', lv:'A1', s:'Richtungen', w:[
 ['links','左边','林克斯','Gehen Sie nach {links}.','请往左走。','x'],
 ['rechts','右边','雷希茨','Gehen Sie nach {rechts}.','请往右走。','x'],
 ['geradeaus','直走','格拉德奥斯','Gehen Sie {geradeaus}.','请直走。','x'],
 ['oben','上面','奥本','Das Buch ist {oben}.','书在上面。','x'],
 ['unten','下面','温滕','Das Bad ist {unten}.','浴室在下面。','x'],
 ['vorne','前面','福尔内','Der Eingang ist {vorne}.','入口在前面。','x'],
 ['hinten','后面','辛滕','Der Garten ist {hinten}.','花园在后面。','x'],
 ['neben','旁边','内本','Die Bank ist {neben} dem Hotel.','银行在酒店旁边。','x'],
 ['zwischen','之间','茨维申','Der Laden ist {zwischen} zwei Häusern.','商店在两栋房子之间。','x'],
 ['gegenüber','对面','格根于贝尔','Die Apotheke ist {gegenüber}.','药店在对面。','x']
]},
{t:'常用副词', lv:'A1', s:'Adverbien', w:[
 ['sehr','很','泽尔','Das ist {sehr} gut.','这非常好。','x'],
 ['auch','也','奥赫','Ich komme {auch}.','我也来。','x'],
 ['nur','只','努尔','Ich habe {nur} fünf Euro.','我只有五欧元。','x'],
 ['schon','已经','舍恩','Er ist {schon} da.','他已经到了。','x'],
 ['noch','还','诺赫','Ich habe {noch} Zeit.','我还有时间。','x'],
 ['immer','总是','伊默','Sie kommt {immer} zu spät.','她总是迟到。','x'],
 ['oft','经常','奥夫特','Wir treffen uns {oft}.','我们经常见面。','x'],
 ['manchmal','有时','曼赫马尔','{Manchmal} koche ich.','有时我做饭。','x'],
 ['nie','从不','尼','Ich trinke {nie} Alkohol.','我从不喝酒。','x'],
 ['wieder','又，再','维德尔','Bis bald {wieder}!','回头见！','x']
]},
{t:'紧急情况', lv:'A1', s:'Notfälle', w:[
 ['die Hilfe','帮助','希尔费','Ich brauche {Hilfe}!','我需要帮助！','n'],
 ['der Notarzt','急救医生','诺特阿尔茨特','Rufen Sie den {Notarzt}!','快叫急救医生！','n'],
 ['die Polizei','警察（机构）','波利查伊','Rufen Sie die {Polizei}!','快报警！','n'],
 ['der Unfall','事故','温法尔','Es gab einen {Unfall}.','发生了一起事故。','n'],
 ['verloren','丢失的','费尔洛伦','Ich habe meinen Pass {verloren}.','我的护照丢了。','a'],
 ['gestohlen','被盗的','格施托伦','Mein Handy wurde {gestohlen}.','我的手机被偷了。','a'],
 ['die Apotheke','药店','阿波泰克','Die {Apotheke} ist geschlossen.','药店关门了。','n'],
 ['das Krankenhaus','医院','克兰肯豪斯','Er ist im {Krankenhaus}.','他在医院。','n'],
 ['der Ausweis','证件','奥斯外斯','Zeigen Sie bitte Ihren {Ausweis}.','请出示您的证件。','n'],
 ['anrufen','打电话','安鲁芬','Ich muss die Polizei {anrufen}.','我得报警。','v']
]},
{t:'银行与邮局', lv:'A1', s:'Bank und Post', w:[
 ['die Bank','银行','班克','Die {Bank} öffnet um neun.','银行九点开门。','n'],
 ['das Konto','账户','孔托','Ich habe ein {Konto}.','我有一个账户。','n'],
 ['die Karte','卡','卡特','Meine {Karte} funktioniert nicht.','我的卡不能用。','n'],
 ['der Automat','自动取款机','奥托马特','Der {Automat} ist kaputt.','取款机坏了。','n'],
 ['die Post','邮局','波斯特','Wo ist die {Post}?','邮局在哪？','n'],
 ['der Brief','信','布里夫','Ich schreibe einen {Brief}.','我在写一封信。','n'],
 ['das Paket','包裹','帕凯特','Das {Paket} ist angekommen.','包裹到了。','n'],
 ['die Briefmarke','邮票','布里夫马克','Ich brauche eine {Briefmarke}.','我需要一张邮票。','n'],
 ['schicken','寄送','施肯','Ich {schicke} dir ein Foto.','我给你发张照片。','v'],
 ['abheben','取（钱）','阿普赫本','Ich möchte Geld {abheben}.','我想取钱。','v']
]},
{t:'电话与网络', lv:'A1', s:'Telefon und Internet', w:[
 ['das Telefon','电话','特雷丰','Das {Telefon} klingelt.','电话响了。','n'],
 ['das Handy','手机','亨迪','Mein {Handy} ist leer.','我手机没电了。','n'],
 ['die Nummer','号码','努默','Wie ist deine {Nummer}?','你的号码是多少？','n'],
 ['die Nachricht','消息','纳赫里希特','Ich habe eine {Nachricht}.','我收到一条消息。','n'],
 ['die E-Mail','电子邮件','伊梅尔','Ich schreibe eine {E-Mail}.','我在写邮件。','n'],
 ['das Internet','互联网','因特内特','Das {Internet} ist langsam.','网速很慢。','n'],
 ['das Passwort','密码','帕斯沃特','Ich habe das {Passwort} vergessen.','我忘了密码。','n'],
 ['senden','发送','曾登','Bitte {senden} Sie mir die Datei.','请把文件发给我。','v'],
 ['klingeln','响铃','克林格恩','Es {klingelt} an der Tür.','门铃响了。','v'],
 ['besetzt','占线的','贝泽茨特','Die Leitung ist {besetzt}.','电话占线。','a']
]}
];
