/* ============================================================
   A2 课程内容
   格式同 A1：[德语, 中文, 读音提示, 例句, 例句译文, 词性]
   ============================================================ */
window.CONTENT_A2 = [
{t:'意见与看法', lv:'A2', s:'Meinung äußern', w:[
 ['die Meinung','意见，看法','迈农','Meiner {Meinung} nach ist das falsch.','在我看来这是错的。','n'],
 ['glauben','相信，认为','格劳本','Ich {glaube}, er kommt später.','我觉得他会晚点到。','v'],
 ['denken','想，认为','登肯','Was {denkst} du darüber?','你觉得怎么样？','v'],
 ['finden','觉得，认为','芬登','Ich {finde} den Film langweilig.','我觉得这电影无聊。','v'],
 ['meinen','认为','迈嫩','Was {meinen} Sie dazu?','您对此怎么看？','v'],
 ['zustimmen','同意','楚施蒂门','Ich kann dir nicht {zustimmen}.','我不能同意你。','v'],
 ['ablehnen','拒绝','阿普莱嫩','Er hat den Plan {abgelehnt}.','他拒绝了这个计划。','v'],
 ['der Grund','原因','格伦特','Was ist der {Grund}?','原因是什么？','n'],
 ['eigentlich','其实，本来','艾根特利希','{Eigentlich} wollte ich nicht kommen.','其实我本来不想来。','x'],
 ['wahrscheinlich','很可能','瓦尔斯海恩利希','Er kommt {wahrscheinlich} zu spät.','他很可能会迟到。','x']
]},
{t:'计划与约定', lv:'A2', s:'Pläne und Verabredungen', w:[
 ['planen','计划','普拉嫩','Wir {planen} eine Reise.','我们在计划一次旅行。','v'],
 ['die Verabredung','约定','费尔阿普雷东','Ich habe eine {Verabredung}.','我有个约。','n'],
 ['sich treffen','见面','希 特雷芬','Wir {treffen} uns morgen.','我们明天见面。','v'],
 ['verschieben','推迟','费尔希本','Wir müssen den Termin {verschieben}.','我们得推迟这个约。','v'],
 ['absagen','取消','阿普扎根','Sie hat die Party {abgesagt}.','她取消了聚会。','v'],
 ['stattfinden','举行','施塔特芬登','Das Konzert {findet} morgen {statt}.','音乐会明天举行。','v'],
 ['rechtzeitig','及时','雷希特蔡蒂希','Komm bitte {rechtzeitig}!','请准时来！','x'],
 ['der Termin','约期，预约','泰尔明','Ich habe einen {Termin} beim Arzt.','我约了医生。','n'],
 ['vereinbaren','商定','费尔艾因巴伦','Wir {vereinbaren} einen Termin.','我们商定一个时间。','v'],
 ['klappen','成功，行得通','克拉彭','Hoffentlich {klappt} es.','希望这事能成。','v']
]},
{t:'职场', lv:'A2', s:'Arbeitswelt', w:[
 ['der Kollege','同事','科莱格','Mein {Kollege} hilft mir oft.','我同事常帮我。','n'],
 ['der Chef','上司','舍夫','Der {Chef} ist heute nicht da.','上司今天不在。','n'],
 ['das Gehalt','工资','格哈尔特','Das {Gehalt} ist gut.','工资不错。','n'],
 ['die Bewerbung','求职申请','贝韦尔本','Ich schreibe eine {Bewerbung}.','我在写求职申请。','n'],
 ['das Vorstellungsgespräch','面试','福尔施泰隆斯格施普雷希','Das {Vorstellungsgespräch} war schwer.','面试很难。','n'],
 ['die Erfahrung','经验','艾尔法龙','Er hat viel {Erfahrung}.','他很有经验。','n'],
 ['die Verantwortung','责任','费尔安特沃通','Das ist meine {Verantwortung}.','这是我的责任。','n'],
 ['die Sitzung','会议','济聪','Die {Sitzung} dauert zwei Stunden.','会议持续两小时。','n'],
 ['der Vertrag','合同','费尔特拉克','Ich habe den {Vertrag} unterschrieben.','我签了合同。','n'],
 ['kündigen','辞职，解约','屈恩迪根','Sie will {kündigen}.','她想辞职。','v']
]},
{t:'健康与就医', lv:'A2', s:'Gesundheit', w:[
 ['die Gesundheit','健康','格尊特海特','{Gesundheit} ist das Wichtigste.','健康最重要。','n'],
 ['die Schmerzen','疼痛','施梅尔岑','Ich habe starke {Schmerzen}.','我疼得厉害。','n'],
 ['das Medikament','药','梅迪卡门特','Nimm das {Medikament} nach dem Essen.','饭后服药。','n'],
 ['die Tablette','药片','塔布莱特','Nimm zwei {Tabletten} am Tag.','每天吃两片。','n'],
 ['untersuchen','检查','温特祖亨','Der Arzt {untersucht} mich.','医生给我检查。','v'],
 ['die Behandlung','治疗','贝汉德隆','Die {Behandlung} dauert lange.','治疗需要很久。','n'],
 ['sich erholen','恢复','希 艾尔霍伦','Ich muss mich {erholen}.','我需要休养。','v'],
 ['die Erkältung','感冒','艾尔克尔通','Ich habe eine {Erkältung}.','我感冒了。','n'],
 ['das Fieber','发烧','菲贝尔','Er hat {Fieber}.','他发烧了。','n'],
 ['impfen','接种疫苗','因普芬','Ich lasse mich gegen Grippe {impfen}.','我去打流感疫苗。','v']
]},
{t:'环境', lv:'A2', s:'Umwelt', w:[
 ['die Umwelt','环境','乌姆韦尔特','Wir müssen die {Umwelt} schützen.','我们必须保护环境。','n'],
 ['der Müll','垃圾','米尔','Bitte trennen Sie den {Müll}.','请分类垃圾。','n'],
 ['recyceln','回收','雷蔡克恩','Wir {recyceln} Plastik.','我们回收塑料。','v'],
 ['die Energie','能源','艾内尔吉','{Energie} wird teurer.','能源变贵了。','n'],
 ['der Klimawandel','气候变化','克利马万德尔','Der {Klimawandel} ist real.','气候变化是真实的。','n'],
 ['schützen','保护','许岑','Wir müssen die Natur {schützen}.','我们必须保护自然。','v'],
 ['verschmutzen','污染','费尔施穆岑','Die Fabrik {verschmutzt} den Fluss.','工厂污染河流。','v'],
 ['der Wald','森林','瓦尔特','Der {Wald} ist groß.','森林很大。','n'],
 ['sparen','节省','施帕伦','Wir müssen Wasser {sparen}.','我们得省水。','v'],
 ['nachhaltig','可持续的','纳赫哈尔蒂希','Das ist {nachhaltig}.','这是可持续的。','a']
]},
{t:'媒体', lv:'A2', s:'Medien', w:[
 ['die Nachrichten','新闻','纳赫里希滕','Ich sehe abends die {Nachrichten}.','我晚上看新闻。','n'],
 ['die Zeitung','报纸','蔡通','Er liest die {Zeitung}.','他在看报纸。','n'],
 ['der Bericht','报道','贝里希特','Der {Bericht} war interessant.','这篇报道很有意思。','n'],
 ['die Sendung','节目','曾东','Die {Sendung} läuft um acht.','节目八点播。','n'],
 ['berichten','报道','贝里希滕','Die Zeitung {berichtet} darüber.','报纸报道了这件事。','v'],
 ['die Werbung','广告','韦尔本','Die {Werbung} nervt.','广告很烦人。','n'],
 ['die Website','网站','韦普赛特','Die {Website} ist langsam.','网站很慢。','n'],
 ['informieren','告知，了解','因福尔米伦','Ich {informiere} mich im Internet.','我在网上了解情况。','v'],
 ['die Quelle','来源','克韦勒','Die {Quelle} ist unbekannt.','来源不明。','n'],
 ['veröffentlichen','发布','费尔厄芬特利亨','Sie {veröffentlichen} den Artikel.','他们发布这篇文章。','v']
]},
{t:'旅行规划', lv:'A2', s:'Reiseplanung', w:[
 ['die Reise','旅行','赖泽','Die {Reise} war schön.','这次旅行很美好。','n'],
 ['der Urlaub','假期','乌尔劳普','Ich brauche {Urlaub}.','我需要休假。','n'],
 ['buchen','预订','布亨','Ich möchte einen Flug {buchen}.','我想订机票。','v'],
 ['der Koffer','行李箱','科费尔','Mein {Koffer} ist zu schwer.','我的箱子太重了。','n'],
 ['die Grenze','边境','格伦策','Wir überqueren die {Grenze}.','我们过境。','n'],
 ['der Pass','护照','帕斯','Zeigen Sie bitte Ihren {Pass}.','请出示护照。','n'],
 ['packen','打包','帕肯','Ich muss noch {packen}.','我还得收拾行李。','v'],
 ['die Sehenswürdigkeit','景点','泽恩斯维尔迪希凯特','Diese {Sehenswürdigkeit} ist berühmt.','这个景点很有名。','n'],
 ['besichtigen','参观','贝济希蒂根','Wir {besichtigen} das Museum.','我们参观博物馆。','v'],
 ['die Unterkunft','住宿','温特库恩夫特','Die {Unterkunft} war günstig.','住宿很便宜。','n']
]},
{t:'节日与传统', lv:'A2', s:'Feste und Traditionen', w:[
 ['das Fest','节日，庆祝','费斯特','Das {Fest} dauert drei Tage.','节日持续三天。','n'],
 ['feiern','庆祝','法伊伦','Wir {feiern} heute.','我们今天庆祝。','v'],
 ['Weihnachten','圣诞节','外纳赫滕','Zu {Weihnachten} bin ich zu Hause.','圣诞节我在家。','x'],
 ['Ostern','复活节','奥斯特恩','{Ostern} ist im Frühling.','复活节在春天。','x'],
 ['das Geschenk','礼物','格申克','Das {Geschenk} gefällt mir.','我喜欢这个礼物。','n'],
 ['der Geburtstag','生日','格布尔特斯塔克','Mein {Geburtstag} ist im Mai.','我生日在五月。','n'],
 ['einladen','邀请','艾因拉登','Ich möchte dich {einladen}.','我想邀请你。','v'],
 ['die Tradition','传统','特拉迪齐翁','Das ist eine alte {Tradition}.','这是个古老的传统。','n'],
 ['der Feiertag','公共假日','法伊尔塔克','Morgen ist ein {Feiertag}.','明天是假日。','n'],
 ['gratulieren','祝贺','格拉图利伦','Ich {gratuliere} dir!','恭喜你！','v']
]},
{t:'人际关系', lv:'A2', s:'Beziehungen', w:[
 ['die Beziehung','关系','贝齐翁','Unsere {Beziehung} ist gut.','我们关系很好。','n'],
 ['der Freund','朋友','弗罗因特','Er ist mein bester {Freund}.','他是我最好的朋友。','n'],
 ['vertrauen','信任','费尔特劳恩','Ich {vertraue} dir.','我相信你。','v'],
 ['sich streiten','争吵','希 施特赖滕','Wir {streiten} uns oft.','我们经常吵架。','v'],
 ['sich verlieben','爱上','希 费尔利本','Er hat sich {verliebt}.','他恋爱了。','v'],
 ['verheiratet','已婚的','费尔海拉特特','Sie ist {verheiratet}.','她已婚。','a'],
 ['ledig','未婚的','莱迪希','Ich bin {ledig}.','我未婚。','a'],
 ['die Hochzeit','婚礼','霍赫蔡特','Die {Hochzeit} ist im Juni.','婚礼在六月。','n'],
 ['sich trennen','分开','希 特伦嫩','Sie haben sich {getrennt}.','他们分手了。','v'],
 ['zusammenleben','同居','楚扎门莱本','Wir wollen {zusammenleben}.','我们想住在一起。','v']
]},
{t:'消费与金钱', lv:'A2', s:'Geld und Konsum', w:[
 ['ausgeben','花费','奥斯给本','Ich gebe zu viel Geld {aus}.','我花钱太多。','v'],
 ['die Ausgabe','支出','奥斯加贝','Die {Ausgaben} sind hoch.','支出很高。','n'],
 ['das Einkommen','收入','艾因科门','Sein {Einkommen} ist niedrig.','他收入低。','n'],
 ['leihen','借','莱恩','Kannst du mir Geld {leihen}?','你能借钱给我吗？','v'],
 ['der Kredit','贷款','克雷迪特','Wir brauchen einen {Kredit}.','我们需要一笔贷款。','n'],
 ['günstig','划算的','屈恩斯蒂希','Das ist sehr {günstig}.','这很划算。','a'],
 ['die Versicherung','保险','费尔济舍龙','Die {Versicherung} ist teuer.','保险很贵。','n'],
 ['die Steuer','税','施托伊尔','Die {Steuern} steigen.','税在涨。','n'],
 ['bar','现金','巴尔','Ich zahle {bar}.','我付现金。','a'],
 ['das Sparbuch','存折','施帕尔布赫','Ich habe ein {Sparbuch}.','我有本存折。','n']
]},
{t:'教育', lv:'A2', s:'Bildung', w:[
 ['die Ausbildung','培训，职业教育','奥斯比东','Er macht eine {Ausbildung}.','他在接受职业培训。','n'],
 ['studieren','上大学','施图迪伦','Sie {studiert} Medizin.','她学医。','v'],
 ['das Studium','大学学业','施图迪乌姆','Das {Studium} dauert vier Jahre.','大学学业四年。','n'],
 ['der Abschluss','学位，毕业','阿普施卢斯','Er hat einen {Abschluss}.','他有学位。','n'],
 ['die Note','分数','诺特','Ich habe eine gute {Note}.','我得了好分数。','n'],
 ['bestehen','通过','贝施泰恩','Ich habe die Prüfung {bestanden}.','我通过考试了。','v'],
 ['durchfallen','不及格','杜尔希法伦','Er ist {durchgefallen}.','他没及格。','v'],
 ['das Fach','科目','法赫','Mathe ist mein bestes {Fach}.','数学是我最好的科目。','n'],
 ['die Kenntnisse','知识','肯特尼瑟','Er hat gute {Kenntnisse}.','他知识扎实。','n'],
 ['unterrichten','授课','温特里希滕','Sie {unterrichtet} Deutsch.','她教德语。','v']
]},
{t:'科技', lv:'A2', s:'Technik', w:[
 ['der Computer','电脑','科姆普尤特','Mein {Computer} ist kaputt.','我电脑坏了。','n'],
 ['das Programm','程序','普罗格拉姆','Das {Programm} läuft nicht.','程序跑不起来。','n'],
 ['die Datei','文件','达泰','Die {Datei} ist zu groß.','文件太大。','n'],
 ['speichern','保存','施派赫恩','Bitte {speichere} die Datei.','请保存文件。','v'],
 ['herunterladen','下载','赫伦特拉登','Ich muss das {herunterladen}.','我得下载这个。','v'],
 ['die App','应用','艾普','Diese {App} ist praktisch.','这个应用很实用。','n'],
 ['das Gerät','设备','格莱特','Das {Gerät} funktioniert nicht.','设备不工作。','n'],
 ['funktionieren','运行，起作用','丰克齐奥尼伦','Es {funktioniert} nicht.','它不好使。','v'],
 ['reparieren','修理','雷帕里伦','Kannst du das {reparieren}?','你能修这个吗？','v'],
 ['die Technik','技术','泰希尼克','Die {Technik} entwickelt sich schnell.','技术发展很快。','n']
]},
{t:'城市生活', lv:'A2', s:'Stadtleben', w:[
 ['das Zentrum','市中心','岑特鲁姆','Wir wohnen im {Zentrum}.','我们住在市中心。','n'],
 ['der Stadtteil','城区','施塔特泰尔','Dieser {Stadtteil} ist ruhig.','这个城区很安静。','n'],
 ['die Miete','租金','米特','Die {Miete} ist hoch.','租金很高。','n'],
 ['umziehen','搬家','乌姆齐恩','Wir {ziehen} nächsten Monat {um}.','我们下个月搬家。','v'],
 ['der Nachbar','邻居','纳赫巴尔','Mein {Nachbar} ist freundlich.','我邻居很友好。','n'],
 ['das Verkehrsmittel','交通工具','费尔凯尔斯米特尔','Welches {Verkehrsmittel} nimmst du?','你坐什么交通工具？','n'],
 ['die Haltestelle','车站','哈尔特施泰勒','Die {Haltestelle} ist dort.','车站在那边。','n'],
 ['das Amt','政府机构','阿姆特','Ich muss zum {Amt}.','我得去政府办事。','n'],
 ['anmelden','登记，注册','安梅尔登','Ich muss mich {anmelden}.','我得去登记。','v'],
 ['die Umgebung','周边环境','乌姆格本','Die {Umgebung} ist schön.','周边很美。','n']
]},
{t:'自然环境', lv:'A2', s:'Natur', w:[
 ['die Natur','自然','纳图尔','Ich liebe die {Natur}.','我热爱大自然。','n'],
 ['der Berg','山','贝尔克','Der {Berg} ist hoch.','这座山很高。','n'],
 ['der See','湖','泽','Wir schwimmen im {See}.','我们在湖里游泳。','n'],
 ['das Meer','海','梅尔','Das {Meer} ist ruhig.','海很平静。','n'],
 ['der Fluss','河','弗卢斯','Der {Fluss} ist breit.','这条河很宽。','n'],
 ['die Landschaft','风景','兰特沙夫特','Die {Landschaft} ist wunderschön.','风景美极了。','n'],
 ['das Feld','田野','费尔特','Die {Felder} sind grün.','田野是绿的。','n'],
 ['der Himmel','天空','希梅尔','Der {Himmel} ist klar.','天空晴朗。','n'],
 ['die Insel','岛','因泽尔','Die {Insel} ist klein.','这个岛很小。','n'],
 ['das Tal','山谷','塔尔','Das {Tal} liegt im Süden.','山谷在南方。','n']
]},
{t:'描述人物', lv:'A2', s:'Personen beschreiben', w:[
 ['freundlich','友好的','弗罗因特利希','Sie ist sehr {freundlich}.','她很友好。','a'],
 ['hilfsbereit','乐于助人的','希尔夫斯贝赖特','Er ist immer {hilfsbereit}.','他总是乐于助人。','a'],
 ['ehrlich','诚实的','艾尔利希','Sei einfach {ehrlich}!','你就诚实点！','a'],
 ['geduldig','耐心的','格杜尔迪希','Der Lehrer ist {geduldig}.','老师很有耐心。','a'],
 ['fleißig','勤奋的','弗莱西希','Sie ist eine {fleißige} Studentin.','她是个勤奋的学生。','a'],
 ['klug','聪明的','克卢克','Das ist ein {kluger} Mann.','这是个聪明人。','a'],
 ['humorvoll','幽默的','胡莫尔福尔','Er ist sehr {humorvoll}.','他很幽默。','a'],
 ['schüchtern','害羞的','许希特恩','Das Kind ist {schüchtern}.','这孩子害羞。','a'],
 ['zuverlässig','可靠的','楚费尔莱西希','Er ist sehr {zuverlässig}.','他很可靠。','a'],
 ['selbstbewusst','自信的','泽尔普斯特贝武斯特','Sie ist {selbstbewusst}.','她很自信。','a']
]},
{t:'交通出行 II', lv:'A2', s:'Unterwegs', w:[
 ['die Autobahn','高速公路','奥托班','Die {Autobahn} ist frei.','高速畅通。','n'],
 ['die Ampel','红绿灯','安佩尔','Die {Ampel} ist rot.','红灯。','n'],
 ['der Führerschein','驾照','菲尔沙因','Ich habe den {Führerschein}.','我有驾照。','n'],
 ['tanken','加油','坦肯','Ich muss noch {tanken}.','我还得加油。','v'],
 ['parken','停车','帕尔肯','Hier darf man nicht {parken}.','这里不许停车。','v'],
 ['der Stau','堵车','施陶','Wir stehen im {Stau}.','我们堵在路上了。','n'],
 ['die Verspätung','晚点','费尔施佩通','Der Zug hat {Verspätung}.','火车晚点。','n'],
 ['umsteigen','换乘','乌姆施泰根','Du musst in Köln {umsteigen}.','你得在科隆换乘。','v'],
 ['das Gleis','站台，轨道','格莱斯','Der Zug fährt von {Gleis} 3.','火车从3站台发车。','n'],
 ['die Ankunft','到达','安库恩夫特','Die {Ankunft} ist um zehn.','到达时间是十点。','n']
]},
{t:'住房与搬家', lv:'A2', s:'Wohnen und Umzug', w:[
 ['der Vermieter','房东','费尔米特尔','Der {Vermieter} ist nett.','房东人不错。','n'],
 ['der Mietvertrag','租约','米特费尔特拉克','Ich habe den {Mietvertrag} gelesen.','我读了租约。','n'],
 ['die Kaution','押金','考齐翁','Die {Kaution} ist hoch.','押金很高。','n'],
 ['die Nebenkosten','附加费用','内本科斯滕','Die {Nebenkosten} sind inklusive.','附加费已含。','n'],
 ['der Balkon','阳台','巴尔孔','Die Wohnung hat einen {Balkon}.','公寓有阳台。','n'],
 ['der Keller','地下室','凯勒','Die Fahrräder stehen im {Keller}.','自行车在地下室。','n'],
 ['renovieren','翻新','雷诺维伦','Wir müssen die Wohnung {renovieren}.','我们得翻新公寓。','v'],
 ['einrichten','布置','艾因里希滕','Wir {richten} die Wohnung neu {ein}.','我们重新布置公寓。','v'],
 ['die Möbel','家具','默贝尔','Die {Möbel} sind neu.','家具是新的。','n'],
 ['der Aufzug','电梯','奥夫楚克','Der {Aufzug} ist kaputt.','电梯坏了。','n']
]},
{t:'饮食文化', lv:'A2', s:'Esskultur', w:[
 ['das Gericht','菜肴','格里希特','Dieses {Gericht} ist typisch deutsch.','这道菜很德国。','n'],
 ['die Zutat','食材','楚塔特','Welche {Zutaten} brauchst du?','你需要哪些食材？','n'],
 ['das Rezept','食谱','雷采普特','Ich habe ein gutes {Rezept}.','我有个好食谱。','n'],
 ['schmecken','尝起来','施梅肯','Es {schmeckt} mir gut.','我觉得很好吃。','v'],
 ['probieren','品尝','普罗比伦','{Probier} mal!','你尝尝！','v'],
 ['vegetarisch','素食的','韦格塔里希','Ich esse {vegetarisch}.','我吃素。','a'],
 ['frisch','新鲜的','弗里施','Das Brot ist {frisch}.','面包是新鲜的。','a'],
 ['die Portion','一份','波尔齐翁','Eine {Portion} Pommes, bitte.','请来一份薯条。','n'],
 ['servieren','上菜','泽尔维伦','Man {serviert} um acht.','八点上菜。','v'],
 ['der Geschmack','味道','格施马克','Der {Geschmack} ist gut.','味道不错。','n']
]},
{t:'目标与进步', lv:'A2', s:'Ziele und Fortschritt', w:[
 ['sich konzentrieren','集中注意力','希 孔岑特里伦','Ich muss mich {konzentrieren}.','我得集中注意力。','v'],
 ['wiederholen','重复','维德霍尔恩','Kannst du das {wiederholen}?','你能重复一遍吗？','v'],
 ['üben','练习','于本','Ich {übe} jeden Tag.','我每天练习。','v'],
 ['das Ziel','目标','齐尔','Mein {Ziel} ist B2.','我的目标是B2。','n'],
 ['erreichen','达到','艾尔赖亨','Ich habe mein Ziel {erreicht}.','我达到了目标。','v'],
 ['der Fortschritt','进步','福特施里特','Du machst gute {Fortschritte}.','你进步很大。','n'],
 ['aufgeben','放弃','奥夫给本','Gib nicht {auf}!','别放弃！','v'],
 ['motiviert','有动力的','莫蒂维尔特','Ich bin {motiviert}.','我很有动力。','a'],
 ['die Geduld','耐心','格杜尔特','Man braucht {Geduld}.','需要耐心。','n'],
 ['schaffen','完成，做到','沙芬','Ich habe es {geschafft}!','我做到了！','v']
]}
];
